---
version: "2"

services:
  # web frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$EXPOSED_PORT:8080"
    depends_on:
      - redis
      - background
    links:
      - redis
    command: gunicorn -b 0.0.0.0:8080 --access-logfile - -w 1 yarnitor:app
    environment:
      REDIS_ENDPOINT: "redis:6379"
      YARN_POLL_SLEEP: 15

  # background collector
  background:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - yarn
    links:
      - redis
      - yarn
    command: yarnitor-background-worker
    environment:
      REDIS_ENDPOINT: "redis:6379"
      YARN_ENDPOINT: "http://yarn:8088"
      YARN_POLL_SLEEP: 60

  # storage between front and backend
  redis:
    image: redis:alpine

  # mock yarn api
  yarn:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - 8088:8088
    command: flask run -h 0.0.0.0 -p 8088
    environment:
      REDIS_ENDPOINT: "redis:6379"
      YARN_ENDPOINT: "http://yarn:8088"
      FLASK_APP: test/mock_yarn.py

  # test command
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - web
      - yarn
    links:
      - web
      - yarn
    command: sleep 0 # no-op placeholder